### ISSUE TITLE
你好，有一个问题想请教你下

### ISSUE THREAD

**Issue by Kimxu** [shaoyuan1943/AndroidRecordAAC#1]
我导入你的这个项目在自己的测试项目中，他报了一个错误。
07-16 16:06:20.357 6748-6805/juli.me.sys E/AndroidRuntime: FATAL EXCEPTION: Thread-290
                                                           Process: juli.me.sys, PID: 6748
                                                           java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/juli.me.sys-1/base.apk"],nativeLibraryDirectories=[/data/app/juli.me.sys-1/lib/arm64, /data/app/juli.me.sys-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libAacEncoder.so"
                                                               at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                               at java.lang.System.loadLibrary(System.java:1076)
                                                               at com.sinaapp.bashell.AacEncoder.<clinit>(AacEncoder.java:36)
                                                               at lwx.linin.aac.AAC.run(AAC.java:65)
                                                               at java.lang.Thread.run(Thread.java:818)

AAC 文件的路径是 lwx.linin.aac
AacEncoder 文件的路径是 com.sinaapp.bashell;
其他的和你项目中的配置都一样，不知道我哪里出错了。希望您帮我看下。麻烦您了

**Comment by Kimxu** [comment]
是因为跟 sharesdk 导入的 .aar 冲突，解决了谢谢

**Comment by shaoyuan1943** [comment]
唔嗯，解决了就好
